export const tools = [
  {
    image: "/image/html.png",
  },
  {
    image: "/image/javascript.png",
  },
  {
    image: "/image/react.png",
  },
  {
    image: "/image/figma.png",
  },
  {
    image: "/image/nextjs.png",
  },
  {
    image: "/image/css.png",
  },
];

export const projects = [
  {
    slug: "plantify-ecommerce-design",
    title: "Plantify",
    category: "web design",
    categoryName: "Diseño Web",
    date: "Julio, 2024",
    coverImage: "/image/Plantify.png",
    image: "/image/PlantifyDesign.png",
  },
  {
    slug: "ganado-link-design",
    title: "GanadoLink",
    category: "web development",
    categoryName: "Desarrollo Web",
    date: "Enero, 2024",
    coverImage: "/image/GanadoLink.png",
    image: "/image/GanadoLinkDesign.png",
    githubWeb: "https://github.com/MarianaTI/ganadolink-web.git",
    githubApi: "https://github.com/Moreno2825/api-ganadoLink.git",
  },
  {
    slug: "ebook-cloud-design",
    title: "eBookCloud",
    category: "web development",
    categoryName: "Desarrollo Web",
    date: "Agosto, 2023",
    coverImage: "/image/eBookCloud.png",
    image: "/image/PlantifyDesign.png",
    githubWeb: "https://github.com/Moreno2825/libreria-desarrollo.git",
    githubApi: "https://github.com/Roman-Chan/api-biblioteca.git",
  },
  // {
  //   slug: "project-events-web",
  //   title: "Events Web",
  //   category: "web development",
  //   categoryName: "Desarrollo Web",
  //   date: "Julio, 2024",
  //   coverImage: "/image/Plantify.png",
  //   image: "/image/PlantifyDesign.png",
  // },
  // {
  //   slug: "mini-projects-online-exam",
  //   title: "Online Math Exam",
  //   category: "web development",
  //   categoryName: "Desarrollo Web",
  //   date: "Junio, 2024",
  //   coverImage: "/image/Plantify.png",
  //   image: "/image/PlantifyDesign.png",
  // },
  // {
  //   slug: "blog-web",
  //   title: "Blog Web",
  //   category: "web development",
  //   categoryName: "Desarrollo Web",
  //   date: "Junio, 2024",
  //   coverImage: "/image/BlogWeb.png",
  //   image: "/image/BlogWeb.png",
  // },
  // {
  //   slug: "ebook-cloud-web",
  //   title: "eBookCloud Web",
  //   category: "web development",
  //   categoryName: "Desarrollo Web",
  //   date: "Agosto, 2023",
  //   coverImage: "/image/eBookCloudWeb.png",
  //   image: "/image/PlantifyDesign.png",
  // },
  // {
  //   slug: "maestro-enarm-web",
  //   title: "Maestro Enarm Web",
  //   category: "web development",
  //   categoryName: "Desarrollo Web",
  //   date: "Mayo, 2023",
  //   coverImage: "/image/MaestroENARMAcademy.png",
  //   image: "/image/PlantifyDesign.png",
  // },
  // {
  //   slug: "maestro-enarm-design",
  //   title: "Maestro Enarm",
  //   category: "web design",
  //   categoryName: "Diseño Web",
  //   date: "Mayo, 2023",
  //   coverImage: "/image/MaestroEnarm.png",
  //   image: "/image/PlantifyDesign.png",
  // },
  // {
  //   slug: "solema-design",
  //   title: "Solema",
  //   category: "web design",
  //   categoryName: "Diseño Web",
  //   date: "Marzo, 2023",
  //   coverImage: "/image/Solema.png",
  //   image: "/image/PlantifyDesign.png",
  // },
  // {
  //   slug: "quick2go-design",
  //   title: "Quick2Go diseño",
  //   category: "web design",
  //   categoryName: "Diseño Web",
  //   date: "Enero, 2023",
  //   coverImage: "/image/Quick2Go.png",
  //   image: "/image/PlantifyDesign.png",
  // },
  // {
  //   slug: "quick2go-web",
  //   title: "Quick2Go",
  //   category: "web development",
  //   categoryName: "Desarrollo Web",
  //   date: "Enero, 2023",
  //   coverImage: "/image/Quick2Go.png",
  //   image: "/image/PlantifyDesign.png",
  // },
];
