import {
  Article,
  ArticleTitle,
  CardContainer,
  CategoryContainer,
  CharacteristicContainer,
  Contact,
  ContactMe,
  Container,
  Content,
  Footer,
  FooterGrid,
  Grid,
  GridAboutMe,
  ImageContainer,
  InfoContent,
  InfoContentAboutMe,
  Information,
  Line,
  PhraseContent,
  SocialMedias,
  SocialMediasContainer,
  TextContent,
  ToolsContainer,
} from "@/styles/Home.style";
import Head from "next/head";
import React, { useState } from "react";
import { projects, tools } from "../../constants";
import CategoryComponent from "@/components/Category/Category";
import CardComponent from "@/components/Card/Card";
import CharacteristicComponent from "@/components/Characteristic/Characteristic";
import { IoLocationOutline } from "react-icons/io5";
import { MdOutlineEmail } from "react-icons/md";
import { FiPhone } from "react-icons/fi";
import { FaDribbble, FaFacebookF, FaGithub, FaLinkedin } from "react-icons/fa";
import { PiPaletteLight, PiHandshakeLight } from "react-icons/pi";
import { IoLanguageOutline } from "react-icons/io5";
import { PiBrainLight } from "react-icons/pi";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  const [selectedCategory, setSelectedCategory] = useState("Todo");

  const navigateToProject = (slug: string) => {
    return router.push({
      pathname: "/[id]",
      query: { id: slug },
    });
  };

  const filteredProjects =
    selectedCategory === "Todo"
      ? projects
      : projects.filter(
          (project) => project.category === selectedCategory.toLowerCase()
        );

  return (
    <Container>
      <Head>
        <title>MarianaDev.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Grid id="home">
        <Information>
          <InfoContent>
            <span>Hola! 👋 Soy Mariana Trujillo</span>
            <h1>FrontEnd Developer UX/UI</h1>
            <p>
              Me encanta crear experiencias digitales fáciles de usar y
              atractivas. Combino el diseño centrado en el usuario con sólidas
              habilidades de programación frontend para crear soluciones nuevas
              y útiles.
            </p>
          </InfoContent>
        </Information>
        <ImageContainer>
          <img src="/image/profile.png" alt="profile-marianadev" />
        </ImageContainer>
      </Grid>
      <ToolsContainer>
        {tools.map((tool, index) => (
          <img key={index} src={tool.image}></img>
        ))}
      </ToolsContainer>
      <GridAboutMe id="aboutme">
        <ImageContainer>
          <img
            src="/image/profile.png"
            width={350}
            alt="profile-marianadev-about-me"
          />
        </ImageContainer>
        <Information>
          <InfoContentAboutMe>
            <h1>Sobre mí</h1>
            <p>
              Soy desarrolladora frontend y diseñadora UX/UI apasionada que ama
              crear experiencias digitales intuitivas y atractivas. Diseño en
              Figma para asegurar una interfaz centrada en el usuario y
              visualmente consistente. Para mis proyectos, utilizo tecnologías
              modernas como Next.js, Emotion/styled, JavaScript, Node.js,
              Express y Firebase.
            </p>
            <p>
              Combino mi creatividad en el diseño con sólidas habilidades
              técnicas para entregar soluciones innovadoras y funcionales que
              superan las expectativas de los usuarios. Disfruto convertir ideas
              en realidad y siempre me esfuerzo por mejorar la satisfacción del
              usuario mediante un diseño cuidadoso y una programación eficiente.
            </p>
            <p>
              Soy responsable y organizada. Siempre estoy emocionada de aprender
              cosas nuevas y mejorar mis habilidades en el desarrollo web y el
              diseño de interfaces de usuario.
            </p>
          </InfoContentAboutMe>
        </Information>
      </GridAboutMe>
      <Content id="projects">
        <h2>Mis proyectos</h2>
        <CategoryContainer>
          <CategoryComponent
            name="Todo"
            onClick={() => setSelectedCategory("Todo")}
            active={selectedCategory === "Todo"}
          />
          <CategoryComponent
            name="Diseño web"
            onClick={() => setSelectedCategory("Web design")}
            active={selectedCategory === "Web design"}
          />
          <CategoryComponent
            name="Desarrollo web"
            onClick={() => setSelectedCategory("Web development")}
            active={selectedCategory === "Web development"}
          />
        </CategoryContainer>
        <CardContainer>
          {filteredProjects.map((project, index) => (
            <CardComponent
              key={index}
              title={project.title}
              category={project.categoryName}
              description={project.date}
              onClick={() => navigateToProject(project.slug)}
            />
          ))}
        </CardContainer>
      </Content>
      <Article>
        <ArticleTitle>
          <h3>Más sobre mí...</h3>
          <span>
            Descubre algunas de las cualidades y habilidades que definen mi
            enfoque y pasión en el trabajo y la vida.
          </span>
        </ArticleTitle>
        <CharacteristicContainer>
          <CharacteristicComponent
            icon={PiPaletteLight}
            label="Creatividad"
            description="Soy una persona altamente creativa, siempre buscando nuevas ideas y soluciones innovadoras en mis proyectos."
          />
          <CharacteristicComponent
            icon={IoLanguageOutline}
            label="Idiomas"
            description="Hablo varios idiomas, incluyendo inglés y español, lo que me permite comunicarme efectivamente en un entorno multicultural."
          />
          <CharacteristicComponent
            icon={PiHandshakeLight}
            label="Trabajo en Equipo"
            description="Disfruto trabajar en equipo y colaborar con otros para lograr objetivos comunes, siempre dispuesto a aprender y enseñar."
          />
          <CharacteristicComponent
            icon={PiBrainLight}
            label="Pensamiento Crítico"
            description="Poseo un fuerte pensamiento crítico, capaz de analizar problemas complejos y encontrar soluciones eficientes y efectivas."
          />
        </CharacteristicContainer>
      </Article>
      <PhraseContent>
        <span>
          “La verdadera creatividad no solo consiste en tener nuevas ideas, sino
          en tener el coraje de seguirlas. Cada desafío es una oportunidad para
          explorar, aprender y transformar lo ordinario en algo extraordinario.”
        </span>
      </PhraseContent>

      <Footer id="footer">
        <Line></Line>
        <FooterGrid>
          <ContactMe>
            <Contact>
              <IoLocationOutline size={25} color="#A555EC" />
              <span>Mérida, Yucatán, México</span>
            </Contact>
            <Contact>
              <MdOutlineEmail size={25} color="#A555EC" />
              <span>marianatrujillo27@hotmail.com</span>
            </Contact>
            <Contact>
              <FiPhone size={25} color="#A555EC" />
              <span>(+52) 999 273 7423</span>
            </Contact>
          </ContactMe>
          <SocialMediasContainer>
            <SocialMedias>
              <a href="https://dribbble.com/MarianaTI">
                <FaDribbble size={25} color="#A555EC" />
              </a>
              <a href="https://github.com/MarianaTI">
                <FaGithub size={25} color="#A555EC" />
              </a>
              <a href="https://www.linkedin.com/in/marianati220503/">
                <FaLinkedin size={25} color="#A555EC" />
              </a>
              <a href="https://www.facebook.com/profile.php?id=100055915908542">
                <FaFacebookF size={25} color="#A555EC" />
              </a>
            </SocialMedias>
            <TextContent>
              <span>Contáctame!</span>
              <span>MarianaDev, 2024.</span>
            </TextContent>
          </SocialMediasContainer>
        </FooterGrid>
      </Footer>
    </Container>
  );
}
