import {
  Circle,
  Container,
  Grid,
  ImageContainer,
  InfoContent,
  Information,
  ToolsContainer,
} from "@/styles/Home.style";
import Head from "next/head";
import React from "react";
import { tools } from "../../constants";

export default function Home() {
  return (
    <Container>
      <Head>
        <title>MarianaDev.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Grid>
        <Information>
          <InfoContent>
            <span>Hello! 👋 I am Mariana Trujillo</span>
            <h1>FrontEnd Developer UX/UI</h1>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua.
            </p>
          </InfoContent>
        </Information>
        <ImageContainer>
          <Circle />
        </ImageContainer>
      </Grid>
      <ToolsContainer>
        {tools.map((tool, index) => (
          <img key={index} src={tool.image}></img>
        ))}
      </ToolsContainer>
      <div>
        
      </div>
    </Container>
  );
}
